# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CraterDetector
                                 A QGIS plugin
 Detects craters from .tif rasters using PyTorch
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-04
        copyright            : (C) 2026 by Riccardo La Grassa
        email                : riccardo.lagrassa@inaf.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CraterDetector class from file CraterDetector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .crater_detector import CraterDetector
    return CraterDetector(iface)
