# -*- coding: utf-8 -*-
"""
/***************************************************************************
 YOLOLens (CraterDetector)
                                 A QGIS plugin
 Detects craters from .tif rasters using PyTorch
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-04
        copyright            : (C) 2026 by Riccardo La Grassa
        email                : riccardo.lagrassa@inaf.it
 ***************************************************************************/
"""

from qgis.utils import plugins
from qgis.core import Qgis, QgsMessageLog


def classFactory(iface):  # pylint: disable=invalid-name
    """Load YOLOLens class from file crater_detector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """

    # 1. Trigger qpip to install deep learning and spatial dependencies
    if 'qpip' in plugins:
        try:
            QgsMessageLog.logMessage("YOLOLens: Checking/Installing dependencies via qpip...", "YOLOLens", Qgis.Info)
            plugins['qpip'].install_requirements()
        except Exception as e:
            QgsMessageLog.logMessage(f"YOLOLens: qpip failed to install dependencies: {str(e)}", "YOLOLens", Qgis.Critical)
    else:
        QgsMessageLog.logMessage("YOLOLens: The 'qpip' plugin is required but not installed/enabled.", "YOLOLens", Qgis.Warning)

    # 2. Defer importing your plugin class until AFTER qpip has executed.
    try:
        # Note: Ensure 'crater_detector.py' is the exact name of your main plugin file
        from .crater_detector import CraterDetector
        return CraterDetector(iface)
    except ImportError as e:
        QgsMessageLog.logMessage(
            f"YOLOLens: Failed to import deep learning libraries. "
            f"Ensure your system has the proper CUDA drivers if using GPU. Error: {e}",
            "YOLOLens",
            Qgis.Critical
        )
        # Re-raise so QGIS interface knows the plugin failed to load gracefully
        raise e
